steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ticktrend-5c1c6/ticktrend-service:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ticktrend-5c1c6/ticktrend-service:$COMMIT_SHA']
# Deploy to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args: ['gcloud', 'run', 'deploy', 'ticktrend-service',
         '--image', 'gcr.io/ticktrend-5c1c6/ticktrend-service:$COMMIT_SHA',
         '--region', 'us-central1',
         '--platform', 'managed',
         '--allow-unauthenticated',
         '--set-env-vars', 'GCP_PROJECT_ID=ticktrend-5c1c6']
images:
- 'gcr.io/ticktrend-5c1c6/ticktrend-service:$COMMIT_SHA'
logsBucket: 'gs://ticktrend-5c1c6-build-logs'  # Explicitly set logs destination
